# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
    ]
