# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_room_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_online',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
